### ISSUE TITLE
Update to egui 0.27.

### ISSUE THREAD

**Issue by tbellembois** [thebashpotato/egui-dashboard-template#2]
Hello,

Thanks for this crate. It makes the styles management much easier.
Can you please update to the latest version of egui?

I have compilation errors that I can not fix myself.

Thanks.

**Comment by thebashpotato** [comment]
Hello,

I'm glad you like the egui-aesthetix crate. I just released version 0.2.3 with support for the new egui and eframe versions (0.27). I also added some new themes, [check it out and give the repo a star](https://github.com/thebashpotato/egui-aesthetix) if you have the time.

I also updated this repository to use the latest version of egui-aesthetix and egui/eframe.

Have a good day.
